"""empty message

Revision ID: 079c9a514936
Revises: 9d50373bfa4c
Create Date: 2019-07-08 16:02:00.958801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079c9a514936'
down_revision = '9d50373bfa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leagues_league_id_key', 'leagues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('leagues_league_id_key', 'leagues', ['league_id'])
    # ### end Alembic commands ###
