"""empty message

Revision ID: 0b57fe1a850c
Revises: 88296c76ead5
Create Date: 2019-07-08 07:15:11.785131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b57fe1a850c'
down_revision = '88296c76ead5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leagues_country_id_key', 'leagues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('leagues_country_id_key', 'leagues', ['country_id'])
    # ### end Alembic commands ###
