"""empty message

Revision ID: 2a8225c633a1
Revises: 734f590a7408
Create Date: 2019-07-07 18:10:25.490855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8225c633a1'
down_revision = '734f590a7408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('club', sa.Column('year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club', 'year', ['year_id'], ['id'])
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['country_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['id'])
    op.drop_constraint(None, 'club', type_='foreignkey')
    op.drop_column('club', 'year_id')
    op.drop_table('year')
    # ### end Alembic commands ###
