"""empty message

Revision ID: 5eb135de2592
Revises: 0196afc47a42
Create Date: 2019-07-07 22:04:20.751998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb135de2592'
down_revision = '0196afc47a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'club', 'year', ['year_id'], ['id'])
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['country_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['id'])
    op.drop_constraint(None, 'club', type_='foreignkey')
    # ### end Alembic commands ###
