"""empty message

Revision ID: 734f590a7408
Revises: 4f1a9c8a5a6d
Create Date: 2019-07-07 13:05:07.030498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f590a7408'
down_revision = '4f1a9c8a5a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['country_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['id'])
    op.drop_table('club')
    # ### end Alembic commands ###
