"""empty message

Revision ID: 8e61153da65c
Revises: ce8c8954b723
Create Date: 2019-09-05 02:21:47.907279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e61153da65c'
down_revision = 'ce8c8954b723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_clubs', sa.Column('G', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_clubs', 'G')
    # ### end Alembic commands ###
