"""empty message

Revision ID: 8e98f71ab828
Revises: c48c3a644f23
Create Date: 2019-07-08 00:51:37.827826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e98f71ab828'
down_revision = 'c48c3a644f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['country_id'])
    op.drop_column('week', 'url')
    op.drop_column('week', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('name', sa.VARCHAR(length=20), nullable=True))
    op.add_column('week', sa.Column('url', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###
