"""empty message

Revision ID: a30bf63dfb64
Revises: cba5eb4ad67a
Create Date: 2019-09-09 11:21:31.664724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30bf63dfb64'
down_revision = 'cba5eb4ad67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_clubs', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_clubs', 'position')
    # ### end Alembic commands ###
