"""empty message

Revision ID: a77e19c56aed
Revises: 8e98f71ab828
Create Date: 2019-07-08 00:52:21.007210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77e19c56aed'
down_revision = '8e98f71ab828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['country_id'])
    op.drop_column('week', 'name')
    op.drop_column('week', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('url', sa.VARCHAR(length=100), nullable=True))
    op.add_column('week', sa.Column('name', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['id'])
    op.drop_table('week_clubs')
    # ### end Alembic commands ###
