"""empty message

Revision ID: ab9930344dc5
Revises: 8e61153da65c
Create Date: 2019-09-08 01:13:12.297534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9930344dc5'
down_revision = '8e61153da65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_clubs', sa.Column('a', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('away_a', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('away_draw', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('away_f', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('away_lost', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('away_win', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('draw', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('f', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('game', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('home_a', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('home_draw', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('home_f', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('home_lost', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('home_win', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('lost', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('pound', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('win', sa.Integer(), nullable=True))
    op.drop_column('week_clubs', 'g')
    op.drop_column('week_clubs', 'G')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_clubs', sa.Column('G', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('week_clubs', sa.Column('g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('week_clubs', 'win')
    op.drop_column('week_clubs', 'pound')
    op.drop_column('week_clubs', 'lost')
    op.drop_column('week_clubs', 'home_win')
    op.drop_column('week_clubs', 'home_lost')
    op.drop_column('week_clubs', 'home_f')
    op.drop_column('week_clubs', 'home_draw')
    op.drop_column('week_clubs', 'home_a')
    op.drop_column('week_clubs', 'game')
    op.drop_column('week_clubs', 'f')
    op.drop_column('week_clubs', 'draw')
    op.drop_column('week_clubs', 'away_win')
    op.drop_column('week_clubs', 'away_lost')
    op.drop_column('week_clubs', 'away_f')
    op.drop_column('week_clubs', 'away_draw')
    op.drop_column('week_clubs', 'away_a')
    op.drop_column('week_clubs', 'a')
    # ### end Alembic commands ###
