"""empty message

Revision ID: c48c3a644f23
Revises: 7c77c192bd81
Create Date: 2019-07-08 00:16:50.382860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48c3a644f23'
down_revision = '7c77c192bd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['country_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'country', ['country_id'], ['id'])
    op.drop_table('week')
    # ### end Alembic commands ###
