"""empty message

Revision ID: cba5eb4ad67a
Revises: ab9930344dc5
Create Date: 2019-09-08 01:48:42.166427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba5eb4ad67a'
down_revision = 'ab9930344dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_clubs', sa.Column('away_pound', sa.Integer(), nullable=True))
    op.add_column('week_clubs', sa.Column('home_pound', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_clubs', 'home_pound')
    op.drop_column('week_clubs', 'away_pound')
    # ### end Alembic commands ###
